import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import DynamicWalletProviderWrapper from "@/components/providers/DynamicWalletProviderWrapper";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.className} antialiased`}
      >
        <DynamicWalletProviderWrapper>
          {children}
        </DynamicWalletProviderWrapper>
      </body>
    </html>
  );
}
